config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#home"
  get "/mylists", to: "pages#home", as: :mylists
  resources :lists, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_one_attached :photo
  validates :photo, presence: true
  belongs_to :list
  validates :title, presence: true
  validates :list_id, presence: true
  validates :comment, length: { minimum: 25 }
  validates :rating, numericality: { only_integer: true }
  validates :rating, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  has_one_attached :background_image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  belongs_to :user
  validates :comment, presence: true
  validates :comment, length: { minimum: 10, maximum: 150 }
  validates :rating, numericality: { only_integer: true }
  validates :rating, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :lists
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :home, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:home], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new(set_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    authorize @bookmark
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end


  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_params
    params.require(:bookmark).permit(:title, :rating, :comment, :photo)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @list = List.new
    @sentence = ""
    if params[:query].present?
      @sentence = "The lists of #{params[:query]}"
      sql_query = <<~SQL
        users.username ILIKE :query
      SQL
      @lists = List.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @sentence = "All lists"
      @lists = policy_scope(List)
    end
  end

  def show
    @reviews = Review.where(list_id: params[:id]).order(created_at: :desc).first(3)
    @review = Review.new
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list_id: params[:id])
    authorize @list
  end

  def new
    @list = List.new
    authorize @list
  end

  def create
    @list = List.new(set_params)
    @list.user = current_user
    authorize @list
    if @list.save
      redirect_to list_path(@list)
    else
      render "index", status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
    authorize @list
  end

  def update
    @list = List.find(params[:id])
    authorize @list
    if @list.update(set_params)
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_params
    params.require(:list).permit(:name, :background_image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @list = List.new
    @lists = List.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @list = List.find(params[:list_id])
    authorize @review
  end

  def create
    @review = Review.new(set_params)
    @list = List.find(params[:list_id])
    authorize @review
    @review.user = current_user
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def set_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%=f.input :title%>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">


  </head>

  <body>
    <%= render "/shared/navbar" %>
    <%= render "/shared/flashes" %>
    <div style="min-height:100vh;" class="mb-5">
    <%= yield %>
    </div>
    <%= render "/shared/footer" %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list, remote: false) do |f| %>
  <%= f.input :name %>
  <%= f.input :background_image, as: :file %>
  <%= f.submit%>
<% end %>

app/views/lists/_review.html.erb
<p class="fw-bold d-flex justify-content-between"><%= review.comment %> <% if policy(review).destroy? %>
                    <%= link_to("delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"ps-5 text-danger text-decoration-none") %>
                    <% end %></p>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/home.html.erb
<div class="banner">
    <div class="container">
      <h1><span id="text-shadow" data-controller="typed-js"></span></h1>
    </div>
  </div>
<div class="container-xl col-12" data-controller="toggle-visible">
  <div class="container-fluid mt-5 ">
    <% if user_signed_in? %>
      <h1 class="d-flex justify-content-between">My lists: <button class="btn fs-5 btn-outline-success" data-action="click->toggle-visible#toggleVisible">Add a list</button></h1>
    <% else %>
      <h2 class="d-flex justify-content-between">SIGN-UP or LOG-IN to start creating lists! <div><%= link_to("SIGN-UP", new_user_registration_path, class: "btn fs-5 btn-outline-success me-2" ) %><%= link_to("Login", new_user_session_path, class: "btn fs-5 btn-outline-success" ) %></div></h2>
    <% end %>
  </div>
  <div class="d-none" data-toggle-visible-target="form">
        <%= render "form", list: @list%>
    </div>
    <div id="card-container" >
    <% if user_signed_in? %>
        <% @lists.each do |list| %>
          <%= link_to(list_path(list), class:"text-decoration-none") do %>
            <% if list.background_image.attached? %>
            <div id="card-movie"style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.background_image.key,
              width: 400, height: 300, crop: :fill) %>')">
              <p id="title"><%= list.name %></p>
              <button>hola</button>
            </div>
            <% else %>
              <div id="card-movie" style= "background-color: gray;">
              <p id="title"><%= list.name %></p>
            </div>
            <% end %>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner">
    <div class="container">
      <h1><span id="text-shadow" data-controller="typed-js"></span></h1>
    </div>
  </div>
<div class="container-xl col-12" data-controller="toggle-visible">
  <div class="container-fluid mt-5 ">
    <h1 class="d-flex justify-content-between">My lists:<button class="btn fs-5 btn-outline-success" data-action="click->toggle-visible#toggleVisible">Add a list</button></h1>
  </div>
  <div class="d-none" data-toggle-visible-target="form">
        <%= render "form", list: @list%>
    </div>
    <div id="card-container" >
        <% @lists.each do |list| %>
          <%= link_to(list_path(list), class:"text-decoration-none") do %>
            <% if list.background_image.attached? %>
            <div id="card-movie"style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.background_image.key,
              width: 400, height: 300, crop: :fill) %>')">
              <p id="title"><%= list.name %></p>
            </div>
            <% else %>
              <div id="card-movie" style= "background-color: gray;">
              <p id="title"><%= list.name %></p>
            </div>
            <% end %>
          <% end %>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="row  justify-content-center mt-5 ">
  <div class="col-sm-12 col-md-3 p-4 bg-secondary rounded bd-gradient">
    <h1>Add a new list</h1>
    <%= render "form", list: @list %>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.background_image.attached? %>
  <div class="banner" style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(@list.background_image.key,
      width: 400, height: 300, crop: :fill) %>')">
    <div class="container">
      <h1><%= @list.name %></h1>
    </div>
  </div>
<% else %>
  <div class="banner" >
    <div class="container">
      <h1><%= @list.name %></h1>
    </div>
  </div>
<% end %>
<div class="row">
  <div id="small-container" data-controller="toggle-visible">
    <div class="d-flex justify-content-between mt-3 mb-3 " >
      <% if @list.user == current_user %>
        <p class="fs-3">My bookmarks</p>
      <% else %>
        <p class="fs-3">The bookmarks from <%= @list.user.username  %></p>
      <% end %>
      <% if @list.user == current_user %>
        <button class="btn fs-5 btn-outline-success" data-action="click->toggle-visible#toggleVisible">Add a movie</button>
      <% end %>
    </div>
    <div class="d-none" data-toggle-visible-target="form">
        <%= render "/bookmarks/form", list: @list, bookmark: @bookmark %>
    </div>
    <div id="card-container-area">
      <% if !@bookmarks.empty? %>
          <% @bookmarks.each do |bookmark| %>
              <div class="card flex-column card-minimum shadow minimumh" data-aos="fade-right" >
                <%= cl_image_tag(bookmark.photo.key, id:"image-from-card") %>
                <div class="d-flex  flex-column justify-content-start card-body">
                  <div class="text-wrap flex-row mb-1 overflow-hidden">
                    <p class="card-title text-start"><strong><%= bookmark.title %></strong>   <span class="text-secondary"><%= bookmark.rating %></span>  <span class="text-warning"><i class="fa-solid fa-star"></i></span>
                      <% if policy(bookmark).destroy? %>
                      <%= link_to("delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"ps-5 text-danger text-decoration-none") %>
                      <% end %>
                    </p>
                  </div>
                  <div class="d-flex justify-content-start overflow-hidden">
                    <p class=" text-secondary text-start"><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
                  </div>
                </div>
              </div>
          <% end %>
      <% else  %>
        <p>No bookmark found!</p>
      <% end %>
    </div>
    <hr>
  <div class="small-container"  data-aos="zoom-in">
    <h3>Reviews</h3>
    <% if @reviews.empty? %>
      <p class="ps-3 text-secondary">No reviews yet. Write the first review to this list!</p>
    <% else %>
        <% @reviews.each do |review|%>
        <div class="flex-row justify-content-between">
          <div >
            <p><% rating = review.rating.to_i %> <!-- assume rating is 4 out of 5 -->
              <% 5.times do |i| %>
                <% if i < rating %>
                  <span class="text-warning"><i class="fa-solid fa-star"></i></span> <!-- filled star for ratings greater than i -->
                <% else %>
                  <i class="fa-regular fa-star"></i> <!-- unfilled star for ratings less than or equal to i -->
                <% end %>
              <% end %>
              <span class="text-secondary f"><em><%=distance_of_time_in_words(review.created_at, Time.now) %> ago</span> by <%= review.user.username %></em>
              </p>
            <p class="fw-bold d-flex justify-content-between"><%= review.comment %> <% if policy(review).destroy? %>
                    <%= link_to("delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"ps-5 text-danger text-decoration-none") %>
                    <% end %></p>
            <hr>
          </div>
          <% end %>
    <% end %>
          <div class="d-flex justify-content-center">
            <div class="bg-white p-3  shadow" id="form">
              <%= render "/reviews/forms", list: @list, review: @review %>
            </div>
          </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
    <div class="container">
      <h1><span id="text-shadow" data-controller="typed-js"></span></h1>
    </div>
  </div>
<div class="container-xl col-12" data-controller="toggle-visible">
  <div class="container-fluid mt-5 ">
    <% if user_signed_in? %>
      <h1 class="d-flex justify-content-between">My lists: <button class="btn fs-5 btn-outline-success" data-action="click->toggle-visible#toggleVisible">Add a list</button></h1>
    <% else %>
      <h2 class="d-flex justify-content-between">SIGN-UP or LOG-IN to start creating lists! <div><%= link_to("SIGN-UP", new_user_registration_path, class: "btn fs-5 btn-outline-success me-2" ) %><%= link_to("Login", new_user_session_path, class: "btn fs-5 btn-outline-success" ) %></div></h2>
    <% end %>
  </div>
  <div class="d-none" data-toggle-visible-target="form">
        <%= render "lists/form", list: @list%>
    </div>
    <div id="card-container" >
    <% if user_signed_in? %>
        <% @lists.each do |list| %>
          <%= link_to(list_path(list), class:"text-decoration-none") do %>
            <% if list.background_image.attached? %>
            <div id="card-movie"style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.background_image.key,
              width: 400, height: 300, crop: :fill) %>')">
              <p id="title"><%= list.name %></p>
            </div>
            <% else %>
              <div id="card-movie" style= "background-color: gray;">
              <p id="title"><%= list.name %></p>
            </div>
            <% end %>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reviews/_forms.html.erb
<%= simple_form_for [list, review], data: { controller: "form-submit" } do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating", action: "click->form-submit#submit"}} %>
  <%= f.submit%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="thing">
      <%= link_to("https://github.com/rmPablo1", target:"_blank") do %>
        <i class="fa-brands fa-github fs-2"></i>
      <% end %>
      <%= link_to("https://www.linkedin.com/in/pablo-rubio-monzo/", target:"_blank") do %>
        <i class="fa-brands fa-linkedin fs-2"></i>
      <% end %>
  </div>
  <p>Made by Pablo Rubio Monzó</p>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? && current_user.photo.attached?
%>
<nav class="navbar bg-white bg-body-tertiary sticky-top" id="">
      <form class="container-fluid">
      <%= image_tag("branding.png", size: "70x70", class:"ms-5 justify-content-start") %>
        <div class="justify-content-end ">
          <%= link_to("All lists", root_path, class: "btn btn-sm") %>
          <%= link_to("My lists", mylists_path, class: "btn btn-sm") %>
          <%= link_to("New list", new_list_path, class: "btn btn-sm") %>
          <%= current_user.username %>
          <%= cl_image_tag(current_user.photo.key,  height: 50, width: 50, class:"avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to("Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete}) %>
          </li>
        </div>
      </form>
      <div>

      </div>
    </nav>
<% elsif user_signed_in? && !current_user.photo.attached? %>
  <nav class="navbar bg-white bg-body-tertiary sticky-top" id="">
      <form class="container-fluid">
      <%= image_tag("branding.png", size: "70x70", class:"ms-5 justify-content-start") %>
        <div class="justify-content-end ">
          <%= link_to("All lists", root_path, class: "btn btn-sm") %>
          <%= link_to("My lists", mylists_path, class: "btn btn-sm") %>
          <%= link_to("New list", new_list_path, class: "btn btn-sm") %>
          <%= current_user.username %>
          <%= link_to("Log out", destroy_user_session_path, class:"text-decoration-none", data: {turbo_method: :delete}) %>
        </div>
      </form>
    </nav>
<% else %>
<nav class="navbar bg-white bg-body-tertiary sticky-top" id="">
      <form class="container-fluid">
      <%= image_tag("branding.png", size: "70x70", class:"ms-5 justify-content-start") %>
        <div class="justify-content-end ">
          <%= link_to("All lists", root_path, class: "btn btn-sm") %>
          <%= link_to("My lists", mylists_path, class: "btn btn-sm") %>
          <%= link_to("New list", new_list_path, class: "btn btn-sm") %>
        </div>
      </form>
    </nav>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_with url: root_path, method: "GET", class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find the lists of a user"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>